### ISSUE TITLE
Directory structure for raptor-resources?

### ISSUE THREAD

**Issue by drgibbon** [evilwan/raptor-chess-interface#2]
I'd like to install the raptor resources manually (actually to make a Slackware package), but I'm not sure what the required directory structure is. Where should they be installed to?

**Comment by evilwan** [comment]
Hi,

The application itself is one self-contained (fat) jar file. To run it, you
will probably need to use a desktop feature to launch java jar's or you
could create a small wrapper shell script that launches the java
application. You can put the application jar anywhere you want on the
filesystem.

As for all other files (resources), they reside under "~/.raptor/". There
are two sets of files that go there:

1) static resources (basically an extraction of the resources jar)
2) version specific resources (for lack of a better description) are copied
at program startup (_every_ startup, so no need to install them) from the
application jar

Basically, if you extract all files from the resources directory in the
resources jar under ~/.raptor/ you will have all files installed. There is
a twist: the pathnames in the jar start with "resources/" but that prefix
has to be stripped while extracting the resources (so
"resources/set/Chessterton/wr.svg" should be extracted to
"~/.raptor/set/Chessterton/wr.svg")

This setup probably does not go well with an installer? Usually an
installer puts application files in a system-wide available place while the
new Raptor setup requires that every user has resources pre-installed
before running the application.

Perhaps it's good to know that the application always extracts the
"resources" directory of the application jar to ~/.raptor That means that
it is possible to move the resources from the resources jar back to the fat
application jar (actually, the previous version of Raptor did not depend on
the exteral resources jar being installed first and copied all resources to
the proper location at startup: that would still be my preferred
organization, but makes for really big installer jars on github)

Finally: it appears that I made a mistake when splitting the resources into
a separate jar (see first issue reported for this project) You might want
to hold off building your final installer until I got that problem sorted
out?

Regards.

On Fri, Jun 26, 2015 at 3:51 AM, drgibbon notifications@github.com wrote:

> I'd like to install the raptor resources manually (actually to make a
> Slackware package), but I'm not sure what the required directory structure
> is. Where should they be installed to?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/evilwan/raptor-chess-interface/issues/2.

## 

---

I think I've got the hang of it now... :w :q :wq :wq! ^d X exit X Q

:quitbye

CtrlAltDel ~~q :~q logout save/quit :!QUIT ^[zz ^[ZZ ZZZZ ^H ^@ ^L ^[c
^# ^E
^X ^I ^T ? help helpquit ^D ^d ^C ^c helpexit ?Quit ?q ^Kx /QY sync

##  halt

**Comment by drgibbon** [comment]
Ahh ok, thanks for the detailed response :) In that case an installer doesn't look like the best way to go until the combined version is out.

**Comment by evilwan** [comment]
Hi,

Just released a new version that fixes the problem of trying to create a file in a (not yet) existing directory.

About the combined version: I think I don't quite follow you there. The first attempt at github was to create one fat jar, including everything the program needs to run, per platform. That should still work if you move the contents of raptor-resources/src/main/resources raptor/src/main/resources  and build just the raptor/pom.xml for your platform.

The main reason for leaving that schema is that most of the jars consists of rather static resource files (images, sounds...) and the available space at github per project is limited (main reason why it took so long to move Raptor from Google Code to Github) So, I selected to come up with a distribution that still provides binaries but with a minimum space on Github. I realize that this is not what you would prefer (keep only one instance of shared files on the system for all users) but it's the best solution I could come up with for the Github problems. Feel free to propose better alternatives! :-)
