### ISSUE TITLE
Request for precompiled 32bit files?

### ISSUE THREAD

**Issue by ByteCommander** [evilwan/raptor-chess-interface#6]
I'm running Ubuntu 15.04 32bit. Would you please also add some 32bit precompiled jar-files to your releases? Or is the only chance to get them to build them myself...

**Comment by evilwan** [comment]
Depends on when you want to have that version ;-)

I'll add 32-bit versions as well, but it may take me a couple of days (weekend) before I can build them. 

If you want to have the version quicker, the only way is to rebuild yourself. Quickest way is probably to unjar the set of dependencies, download the 32-bit version of SWT for your platform and replace the 64-bit version in the extracted dependencies with the 32-bit version that you downloaded. Thereafter, a build for profile linux should produce the fat jar you need.

**Comment by ByteCommander** [comment]
No hurry, I'll wait. I'm using eboard at the moment, which I don't like much, but it will do its job a few days more... ;-) Thank you for responding!

**Comment by evilwan** [comment]
There are now 32 bit versions for download for all3 platforms.

Emjoy!
